config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope '(:locale)', locale: /en|de/ do
    devise_for :user, controllers: {confirmations: 'user/confirmations',
                                    passwords:     'user/passwords',
                                    registrations: 'user/registrations',
                                    sessions:      'user/sessions',
                                    unlocks:       'user/unlocks'}

    devise_scope :user do
      get :user, to: 'user/registrations#show', as: nil # Helper user_registration_path is already generated by Devise (as POST, but seems to be OK for GET, too)
    end

    resources :users
    resources :pages

    [403, 404, 422, 500].each do |code|
      get code, to: 'errors#show', code: code
    end

    root 'homepage#show'

  end
end

app/views/layouts/_jump_links.html.slim
.navbar-inverse
  ul#jump_links.nav.navbar-nav
    - unless current_page?(root_path)
      li = link_to t('.home_page'), root_path, accesskey: 0, class: 'sr-only', id: 'jump_to_home_page'
    li = link_to t('.content'), '#headline_title', accesskey: 1, class: 'sr-only', id: 'jump_to_content'

app/views/layouts/_navigation.html.slim
nav#navigation.container
  .navbar.yamm.navbar-inverse.navbar-fixed-top
    h2#navigation_title.sr-only = t '.navigation'

    .container
      .navbar-header
        // Place brand before the "Toggle navigation" button to have an intuitive focus order (on the Bootstrap examples page it's after the button which seems unintuitive)
        = link_to root_path, class: home_link_class, id: 'logo' do
          = t('.home')
          span.sr-only =< t('.go_to_home_page')

        button#toggle_navigation.navbar-toggle.collapsed aria-controls="bs-navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
          span.menu-text = t '.toggle_navigation'
          span.menu-icon
            span.icon-bar
            span.icon-bar
            span.icon-bar

      #navbar.navbar-collapse.collapse aria-expanded="false"
        h3.sr-only = t '.content_navigation'

        ul#content_navigation.nav.navbar-nav
          - @root_pages.each do |page|
            - if (children = page.children).any?
              = navigation_group page.navigation_title_or_title, page_path(page) do
                - page.children.each do |child|
                  = navigation_item child.navigation_title_or_title, page_path(child)
            - else
              = navigation_item page.navigation_title_or_title, page_path(page)

        h3.sr-only = t '.meta_navigation'

        ul#meta_navigation.nav.navbar-nav.navbar-right
          == render 'layouts/resource_navigation_group', resource_class: Page if can? :crud, Page
          == render 'layouts/resource_navigation_group', resource_class: User if can? :crud, User

          - if user_signed_in?
            = navigation_group user_avatar(t('.user_menu')), user_registration_path, "#{icon :user, type: :fa} #{t '.show_account'}" do
              = navigation_item edit_user_registration_path do
                = icon :edit, type: :fa
                =< t '.edit_account'

              li
                = link_to destroy_user_session_path, method: :delete do
                  = icon('sign-out', type: :fa)
                  =< t('.log_out')

              - if can? :access, :rails_admin
                li.divider role="presentation"

                li = link_to rails_admin_path(locale: :en) do
                  = icon(:gears, type: :fa)
                  =< t('.admin')

          - else
            = navigation_item new_user_registration_path do
              span.visible-sm-inline-block = icon 'user-plus', type: :fa
              span.hidden-sm = t '.sign_up'

            = navigation_mega t('.sign_in'), new_user_session_path do
              .row = render 'devise/sessions/form', resource: User.new, display: :small

          li#language_chooser.dropdown
            = link_to flag(current_locale_flag, t('.choose_language')), '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown', 'aria-expanded': false

            ul.dropdown-menu
              li lang="en"
                = link_to locale: 'en' do
                  => flag(:gb)
                  | Show page in english

              li lang="de"
                = link_to locale: 'de' do
                  => flag(:de)
                  | Seite auf Deutsch anzeigen

  #breadcrumbs.breadcrumb
    h3 #{t '.you_are_here'}:

    ol.breadcrumb
      li = link_to t('app.acronym'), root_path
      = render_breadcrumbs

app/views/layouts/_resource_navigation_group.html.slim
= navigation_group resource_class.model_name.human(count: :other), send("#{resource_class.to_s.underscore.pluralize}_path"), "#{icon :bars, type: :fa} #{t 'actions.resources_list', resources: resource_class.model_name.human(count: :other)}" do
  - if can? :create, resource_class
    = navigation_item send("new_#{resource_class.to_s.underscore}_path") do
      = icon :plus, type: :fa
      =< t 'actions.new_resource', resource: resource_class.model_name.human

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    = title_tag

    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta name="description" content="#{yield(:description)}"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = auto_discovery_link_tag(:atom, pages_path(format: :atom), title: Page.model_name.human(count: :other))

  body class=body_css_classes
    header
      == render 'layouts/jump_links'

      h1.sr-only = t '.header'
      == render 'layouts/navigation'

    main#main.container
      .row
        .col-md-12
          == yield

    footer#footer
      h1.sr-only = t '.footer'
      .container
        .row
          .col-xs-6.slogan.atom
            p
              => link_to(t('app.name'), 'https://github.com/jmuheim/base/') + ':'

              span.hidden-xs = t 'app.slogan'

              =< link_to pages_path(format: :atom) do
                = icon :rss, 'Atom Feed', type: :fa

          .col-xs-4.copyright
            p &copy; 2015 #{link_to t('org.name'), 'http://www.muheimwebdesign.ch/'}